version: "3.9"

services:
  mongo:
    image: mongo:5.0.2
    container_name: base_c_mongodb
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${DATABASE_PORT}

  redis:
    image: redis:6.2.5
    container_name: base_c_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data/redis
    ports:
      - ${REDIS_PORT}

  app: &app
    build:
      context: .
    depends_on:
      - mongo
      - redis

  base_c:
    <<: *app
    container_name: base_c
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - ./:/app

  runner:
    <<: *app
    env_file:
      - .env
    command: /bin/bash

volumes:
  mongo:
  redis:

networks: 
  default: 
    external: 
      name: bases_network
